<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-ELS3U9TE" failures="1" tests="2" name="Default test" time="14.884" errors="0" timestamp="2021-01-18T09:08:49 SGT">
  <testcase classname="Validations.HomePageValidation" name="TC02_Validate4dayforecast_dayaftertomorrowtempfromAPI" time="7.142">
    <failure type="org.json.JSONException" message="JSONObject[&amp;quot;update_timestamp&amp;quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["update_timestamp"] not found.
at org.json.JSONObject.get(JSONObject.java:573)
at org.json.JSONObject.getString(JSONObject.java:836)
at AutomationModules.APITest.RegistrationSuccessful(APITest.java:54)
at Validations.HomePageValidation.TC02_Validate4dayforecast_dayaftertomorrowtempfromAPI(HomePageValidation.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC02_Validate4dayforecast_dayaftertomorrowtempfromAPI -->
  <testcase classname="Validations.HomePageValidation" name="TC01_StartBrowserandValidatePageTitle" time="1.688"/>
  <testcase classname="Validations.HomePageValidation" name="TC03_Validate4dayforecast_dayaftertomorrowtemp" time="0.0">
    <ignored/>
  </testcase> <!-- TC03_Validate4dayforecast_dayaftertomorrowtemp -->
</testsuite> <!-- Default test -->
